apiVersion: v1
kind: Service
metadata:
  labels:
    app: reactjs-web
  name: reactjs-web
  namespace: my-application
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: reactjs-web
  type: ClusterIP
